### ISSUE TITLE
大佬，请教一下，如何渲染后台返回的dicom资源呢？

### ISSUE THREAD

**Issue by mojiefong** [jianyaoo/vue-cornerstone-demo#10]

**Comment by jianyaoo** [comment]
如果后台接口(假设为 /api/xxxx/xxxx)返回的是一个dicom文件流，则将在案例中的ImageId改为下面接口即可：
```
const imageLoaderTheme = 'wadouri'; // 取决于文件流的方式
const imageId = `${imageLoaderTheme}:${HOST}/api/xxxx/xxxx`;
```
ImageIds由多个ImageId的接口组成

**Comment by mojiefong** [comment]
> 如果后台接口(假设为 /api/xxxx/xxxx)返回的是一个dicom文件流，则将在案例中的ImageId改为下面接口即可：
> 
> ```
> const imageLoaderTheme = 'wadouri'; // 取决于文件流的方式
> const imageId = `${imageLoaderTheme}:${HOST}/api/xxxx/xxxx`;
> ```
> 
> ImageIds由多个ImageId的接口组成

好的，感谢大佬、我试试
